#' pamPatterns: Pattern Analysis for Passive Acoustic Monitoring Data
#'
#' The pamPatterns package provides functions to read acoustic detection data
#' (e.g., from BirdNET), calculate a variety of pattern metrics, flag
#' potentially problematic species detections based on these patterns,
#' and suggest data-driven thresholds for review.
#'
#' @section Core functions:
#' The main functions you'll use are:
#' \itemize{
#'   \item \code{\link{read_birdnet_data}}: To load and preprocess your BirdNET CSV files.
#'   \item \code{\link{extract_audiomoth_id}}: A helper to get AudioMoth IDs from paths.
#'   \item \code{\link{calculate_pattern_metrics}}: To compute all quantitative indicators.
#'   \item \code{\link{suggest_thresholds}}: To get data-driven threshold suggestions.
#'   \item \code{\link{flag_species}}: To apply thresholds and calculate review scores.
#'   \item \code{\link{print_metrics_summary}}: To quickly view results.
#'   \item \code{\link{export_metrics}}: To save your metrics table.
#' }
#' @keywords internal
"_PACKAGE"

# The following block is automatically generated by usethis::use_pipe()
# or usethis::use_import_from() and should not be manually edited.
## usethis namespace: start
#' @importFrom dplyr %>%
## usethis namespace: end
NULL # This NULL is typically for the import block and can remain if usethis puts it there.
